name: PullRequest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build frontend
      run: 'docker build frontend -t gcr.io/crafting-playground/demo/hello-k8s/frontend:pr-$(jq -cMr .pull_request.number "$GITHUB_EVENT_PATH")'
    - name: Build backend
      run: 'docker build backend -t gcr.io/crafting-playground/demo/hello-k8s/backend:pr-$(jq -cMr .pull_request.number "$GITHUB_EVENT_PATH")'
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: ${{ secrets.GCP_OIDC_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Configure docker
      run: gcloud auth configure-docker
    - name: Push frontend
      run: 'docker push gcr.io/crafting-playground/demo/hello-k8s/frontend:pr-$(jq -cMr .pull_request.number "$GITHUB_EVENT_PATH")'
    - name: Push backend
      run: 'docker push gcr.io/crafting-playground/demo/hello-k8s/backend:pr-$(jq -cMr .pull_request.number "$GITHUB_EVENT_PATH")'
